/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mx_dengxinliang_imageeffects_MainActivity_FilterAdapter */

#ifndef _Included_com_mx_dengxinliang_imageeffects_MainActivity_FilterAdapter
#define _Included_com_mx_dengxinliang_imageeffects_MainActivity_FilterAdapter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
