/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mx_dengxinliang_imageeffects_MainActivity_PictureProcess */

#ifndef _Included_com_mx_dengxinliang_imageeffects_MainActivity_PictureProcess
#define _Included_com_mx_dengxinliang_imageeffects_MainActivity_PictureProcess
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
